### ISSUE TITLE
Providing sample data possible?

### ISSUE THREAD

**Issue by beniroquai** [samhitech/microEye#3]
Hey @samhitech, thanks a lot for publishing the source code for your tool! :-) 
I was trying to use it with the standard dataset from thunderstorm: https://zitmen.github.io/thunderstorm/
but it failed with several errors - I think they originate from not finding any events in a frame (?) Will look into that now. 
I was wondering if you have a working dataset that can be reconstructed with the data viewer. 

Thanks a lot!

**Comment by samhitech** [comment]
Hello @beniroquai, and sorry for the late reply.
Thanks, we are trying our best to make such scientific tools open-source and readily available.
I suggest trying out the RAW data of Gatta-PAINT 80R rulers available at [www.gattaquant.com](https://www.gattaquant.com/files/GATTA-PAINT-80R-RAW.zip).

The tiff files should be three-dimensional like TYX, ZYX, ... etc.
You should adjust the relative detection threshold and filters used (DoG or Bandpass), and do not forget to check "Enable real-time localization". 
Phasor-based fitting should work out of the box, and fit based on pyfit3Dcspline might not execute properly if an Nvidia GPU is present and the CUDA toolkit is not installed and set correctly ([numba CUDA guide](https://numba.pydata.org/numba-doc/latest/cuda/overview.html#programming-model)).

The rest should work smoothly, just set your desired fitting method, ROI size, pixel size ... etc, and execute "Localize".
Let me know how it goes, best of luck!

**Comment by beniroquai** [comment]
Hey @samhitech, thanks for your help. I had problems getting it to work with our data (It did not even start the localization..not sure why though..). I fixed some minor issues in my branch. It's now
art of [imswitch/imswitch at master · openUC2/ImSwitch](https://github.com/openUC2/ImSwitch) and runs reconstructions in real-time. More a gimmick, but fun! :) Hope to publish that soon somehow with some UC2 cubes https://github.com/openUC2/UC2-GIT/ :D
